### ISSUE TITLE
Dialyzer crash with macros, structs, and modules

### ISSUE THREAD

**Issue by chrismcg** [fishcakez/dialyze#10]
As discussed on IRC I'm opening an issue here for this till we can figure out where best to put it.

Sample app that causes the crash is at:

https://github.com/chrismcg/dial_test

`mix deps.get && mix compile && mix dialyze` will trigger the problem. There's some comments in the module that document some other things I tried that didn't make dialyzer crash.

**Comment by fishcakez** [comment]
This is a bug in OTP. I have minimised this to an Erlang module that will crash dialyzer:

```erlang
-module(dial_test).

-export([function/0]).

function() ->
    case #{} of
        #{} -> ok;
        Mod -> Mod:function(#{literal => map}, another_arg)
    end.
```

Could you report this on http://bugs.erlang.org?

**Comment by chrismcg** [comment]
Done. http://bugs.erlang.org/browse/ERL-68
