### ISSUE TITLE
exit with non-zero code on warnings

### ISSUE THREAD

**Issue by sasa1977** [fishcakez/dialyze#13]
First of all thank you for this great library!

Do you think it would make sense to exit with non-zero when there are warnings? For example, I'm using this in my CI, and would like to fail if dialyzer is not happy. Currently I have to do some bash gimmicks and analyze stderr output to make it happen. With the non-zero exit code then it would just work.

If you think this makes sense, I'd be happy to prepar a PR.

**Comment by fishcakez** [comment]
Go for it!
