### ISSUE TITLE
Elixir 1.1.0-beta gives warning

### ISSUE THREAD

**Issue by eksperimental** [fishcakez/dialyze#8]
```sh
$ elixir --version
Elixir 1.1.0-beta

$ mix
warning: the archive dialyze-0.1.4 requires Elixir "~> 0.14.3 or ~> 0.15.0 or ~> 1.0.0 or ~> 1.1.0-dev" but you are running on v1.1.0-beta
```

**Comment by fishcakez** [comment]
Did you try 0.2.0?

**Comment by eksperimental** [comment]
I'm a bit lost. i am getting this in project i just created with `mix new`

**Comment by fishcakez** [comment]
Can you try upgrading dialyze from 0.1.4 to 0.2.0?

**Comment by eksperimental** [comment]
sorry, but how do i do that, since dialyze is not a dependency in my project.
Can it be a dependency to elixir itself?

```
$ mix deps.get
warning: the archive dialyze-0.1.4 requires Elixir "~> 0.14.3 or ~> 0.15.0 or ~> 1.0.0 or ~> 1.1.0-dev" but you are running on v1.1.0-beta
All dependencies up to date

$ mix deps.get
warning: the archive dialyze-0.1.4 requires Elixir "~> 0.14.3 or ~> 0.15.0 or ~> 1.0.0 or ~> 1.1.0-dev" but you are running on v1.1.0-beta
All dependencies up to date
```

**Comment by ericmj** [comment]
@eksperimental How did you install dialyze? You can clone the repo and run `mix install` to install a newer version.

**Comment by ericmj** [comment]
The current version requirement won't match "1.0.0-beta" though.

**Comment by eksperimental** [comment]
thanks @ericmj I forgot I had install it from this repo.
So, is there a way when i bump into an issue like this to know where a package is being loaded from? something like the unix `which` command

**Comment by ericmj** [comment]
@eksperimental The error message says it's an archive, all archives are in ~/.mix/archives.

**Comment by eksperimental** [comment]
beautiful, thanks a lot @ericmj  and @fishcakez
